matrix:
   include:
      - language: python
        python: 3.2
        install:
           - pip install flask flask_restful flask_cors flask_jsonpify flask_script flask_migrate
           - pip install boto3
        script:
           - py.test
